FUNCTION zedu##_order_check.
*" IMPORTING IV_CUST_ID TYPE ZEDU_CUSTID
*"           IV_PROD_ID TYPE ZEDU_PRODID
*"           IV_QUANTITY TYPE ZEDU_QTY
*" EXPORTING EV_PRICE TYPE ZEDU_PRICE
*" EXCEPTIONS INVALID_CUST INVALID_PROD INVALID_QTY

* TODO 1: 고객 존재 여부를 검사하고 INVALID_CUST를 발생시키세요.
* TODO 2: 제품과 단가를 검사하고 INVALID_PROD를 발생시키세요.
* TODO 3: 수량이 0 이하면 INVALID_QTY를 발생시키세요.
ENDFUNCTION.
